// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDirectiryOfDepartments.DataServices.Context;

#nullable disable

namespace WebDirectiryOfDepartments.DataServices.Migrations
{
    [DbContext(typeof(DirectiryOfDepartmentsContext))]
    [Migration("20240225130642_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebDirectiryOfDepartments.Core.Model.DirectoryUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentDirectoryUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentDirectoryUnitId");

                    b.ToTable("DirectoryUnits");
                });

            modelBuilder.Entity("WebDirectiryOfDepartments.Core.Model.DirectoryUnit", b =>
                {
                    b.HasOne("WebDirectiryOfDepartments.Core.Model.DirectoryUnit", "ParentDirectoryUnit")
                        .WithMany("ChildDirectoryUnits")
                        .HasForeignKey("ParentDirectoryUnitId");

                    b.Navigation("ParentDirectoryUnit");
                });

            modelBuilder.Entity("WebDirectiryOfDepartments.Core.Model.DirectoryUnit", b =>
                {
                    b.Navigation("ChildDirectoryUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
